import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import '@mantine/core/styles.css';
import { MantineProvider } from '@mantine/core'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Work management App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <MantineProvider>
          {children}
        </MantineProvider>
      </body>
    </html>
  )
}
